language: rust

cache: cargo

rust:
  - stable
  - beta
  - nightly

install: |
  if [ "$TRAVIS_RUST_VERSION" != nightly ]; then
    rustup component add clippy
  fi

script:
  - cargo test --all --all-features
  - cargo test --all --all-features --release
  - |
    if [ "$TRAVIS_RUST_VERSION" != nightly ]; then
      cargo clippy
    fi

deploy:
  provider: script
  script:
    - cargo publish --token "${CRATES_IO_TOKEN}"
  on:
    tags: true
    all_branches: true
    condition: $TRAVIS_RUST_VERSION = stable

notifications:
  email:
    on_success: never
