language: rust

cache: cargo

rust:
  - stable
  - beta
  - nightly

script:
  - cargo test
  - cargo clippy

deploy:
  provider: script
  script:
    - cargo publish --token "${CRATES_IO_TOKEN}"
  on:
    tags: true
    all_branches: true
    condition: $TRAVIS_RUST_VERSION = stable

notifications:
  email:
    on_success: never
