[package]
name = "vcontrol"
description = "A library for communication with Viessmann heating controllers."
version = "0.3.4"
edition = "2021"
authors = ["Markus Reiter <me@reitermark.us>"]
documentation = "https://docs.rs/vcontrol"
repository = "https://github.com/reitermarkus/vcontrol-rs"
homepage = "https://github.com/reitermarkus/vcontrol-rs"
keywords = ["heating", "control", "automation"]
categories = ["hardware-support"]
exclude = ["/.travis.yml"]
license = "MIT OR Apache-2.0"
readme = "ReadMe.md"

[features]
cli = ["actix-rt", "clap", "serde_json", "env_logger", "webthing", "impl_json_schema"]
impl_json_schema = ["schemars"]

[dependencies]
actix-rt = { version = "1.1", optional = true }
clap = { version = "2.33", optional = true }
chrono = "0.4"
log = "0.4"
phf = { version = "0.10", features = ["serde"] }
phf_shared = "0.10"
serial = "0.4"
serial-core = "0.4"
serde = { version = "1", features = ["derive"] }
serde_json = { version = "1", optional = true }
serde_yaml = { version = "0.8", optional = true }
env_logger = { version = "0.9.0", optional = true }
webthing = { version = "0.14.0", optional = true }
schemars = { version = "0.8.8", optional = true }

[[example]]
name = "cat"
required-features = ["env_logger"]

[[example]]
name = "scan"
required-features = ["serde_yaml"]

[target.'cfg(unix)'.dependencies]
libc = "0.2"

[build-dependencies]
chrono = "0.4"
phf_shared = "0.10"
phf_codegen = "0.10"
serde = { version = "1", features = ["derive"] }
serde_yaml = "0.8"

[patch.crates-io]
# phf = { path = "./rust-phf/phf" }
phf = { git = "https://github.com/reitermarkus/rust-phf", branch = "serialize-map" }
