device: V200KW2_6
commands:
  system_type:
    addr: 0x00F8
    unit: DT
    mode: read
  system_time:
    addr: 0x088E
    unit: TI
    mode: read_write
  operatingmode:
    addr: 0x3301
    unit: E_BA2
    mode: read_write
  energysavermode_state:
    addr: 0x3302
    unit: E_ST
    mode: read_write
  partymode_state:
    addr: 0x3303
    unit: E_ST
    mode: read_write
  partymode_temp:
    addr: 0x3308
    unit: T1U
    mode: read_write
  vacationmode_state:
    addr: 0x3535
    unit: B_FB
    mode: read_write
  vacationmode_date_departure:
    addr: 0x3309
    unit: TI
    mode: read_write
  vacationmode_date_return:
    addr: 0x3311
    unit: TI
    mode: read_write
  boiler_temp_state:
    addr: 0x083B
    unit: E_TS
    mode: read
  boiler_temp_actual:
    addr: 0x0802
    unit: TD
    mode: read
  boiler_temp_desired:
    addr: 0x5502
    unit: TD
    mode: read
  boiler_temp_lowpass:
    addr: 0x0810
    unit: TD
    mode: read
  storagetank_chargingpump_state:
    addr: 0x0845
    unit: E_ST
    mode: read
  storagetank_temp_lowpass:
    addr: 0x0812
    unit: TD
    mode: read
  burner_state_1:
    addr: 0x0842
    unit: E_ST
    mode: read
  burner_state_2:
    addr: 0x0849
    unit: E_ST
    mode: read
  burner_state_error:
    addr: 0x0883
    unit: E_ST
    mode: read
  burner_starts:
    addr: 0x088A
    unit: CO
    mode: read
  burner_hours_1:
    addr: 0x08A7
    unit: HS
    mode: read
  outside_temp_state:
    addr: 0x083A
    unit: E_TS
    mode: read
  outside_temp_actual:
    addr: 0x0800
    unit: TD
    mode: read
  outside_temp_mixed:
    addr: 0x5527
    unit: TD
    mode: read
  outside_temp_lowpass:
    addr: 0x5525
    unit: TD
    mode: read
  circulationpump_state:
    addr: 0x0846
    unit: E_ST
    mode: read
  circulationpump_timer_mon:
    addr: 0x2200
    unit: CT
    mode: read_write
  circulationpump_timer_tue:
    addr: 0x2208
    unit: CT
    mode: read_write
  circulationpump_timer_wed:
    addr: 0x2210
    unit: CT
    mode: read_write
  circulationpump_timer_thu:
    addr: 0x2218
    unit: CT
    mode: read_write
  circulationpump_timer_fri:
    addr: 0x2220
    unit: CT
    mode: read_write
  circulationpump_timer_sat:
    addr: 0x2228
    unit: CT
    mode: read_write
  circulationpump_timer_sun:
    addr: 0x2230
    unit: CT
    mode: read_write
  hotwater_temp_actual:
    addr: 0x0804
    unit: TD
    mode: read
  hotwater_temp_desired:
    addr: 0x6300
    unit: T1U
    mode: read_write
  hotwater_release:
    addr: 0x3500
    len: 22
    pos: 8
    unit: E_WWF
    mode: read
  hotwater_timer_mon:
    addr: 0x3100
    unit: CT
    mode: read_write
  hotwater_timer_tue:
    addr: 0x3108
    unit: CT
    mode: read_write
  hotwater_timer_wed:
    addr: 0x3110
    unit: CT
    mode: read_write
  hotwater_timer_thu:
    addr: 0x3118
    unit: CT
    mode: read_write
  hotwater_timer_fri:
    addr: 0x3120
    unit: CT
    mode: read_write
  hotwater_timer_sat:
    addr: 0x3128
    unit: CT
    mode: read_write
  hotwater_timer_sun:
    addr: 0x3130
    unit: CT
    mode: read_write
  heatingcircuit_mode:
    addr: 0x3500
    len: 22
    pos: 1
    unit: E_BA
    mode: read
  heatingcircuit_timer:
    addr: 0x3500
    len: 22
    pos: 2
    unit: E_TIMER
    mode: read
  heatingcircuit_pump_state:
    addr: 0x3906
    unit: E_ST
    mode: read
  heatingcircuit_pump_command:
    addr: 0x3500
    len: 22
    pos: 10
    unit: E_HKP
    mode: read
  heatingcircuit_rp_temp_state:
    addr: 0x083F
    unit: E_TS
    mode: read
  heatingcircuit_rp_temp_lowpass:
    addr: 0x081A
    unit: TD
    mode: read
  heatingcircuit_fp_temp_state:
    addr: 0x0840
    unit: E_TS
    mode: read
  heatingcircuit_fp_temp_actual:
    addr: 0x3900
    unit: TD
    mode: read
  heatingcircuit_fp_temp_desired:
    addr: 0x3500
    len: 22
    pos: 12
    unit: TD
    mode: read
  heatingcircuit_fp_temp_lowpass:
    addr: 0x0818
    unit: TD
    mode: read
  heatingcircuit_timer_mon:
    addr: 0x3000
    unit: CT
    mode: read_write
  heatingcircuit_timer_tue:
    addr: 0x3008
    unit: CT
    mode: read_write
  heatingcircuit_timer_wed:
    addr: 0x3010
    unit: CT
    mode: read_write
  heatingcircuit_timer_thu:
    addr: 0x3018
    unit: CT
    mode: read_write
  heatingcircuit_timer_fri:
    addr: 0x3020
    unit: CT
    mode: read_write
  heatingcircuit_timer_sat:
    addr: 0x3028
    unit: CT
    mode: read_write
  heatingcircuit_timer_sun:
    addr: 0x3030
    unit: CT
    mode: read_write
  heatingcurve_niveau:
    addr: 0x3304
    unit: HKLN
    mode: read_write
  heatingcurve_incline:
    addr: 0x3305
    unit: HKLS
    mode: read_write
  roomtemp_day_desired:
    addr: 0x3306
    unit: T1U
    mode: read_write
  roomtemp_night_desired:
    addr: 0x3307
    unit: T1U
    mode: read_write
  frostwarning_state:
    addr: 0x3500
    unit: B_FW
    len: 22
    pos: 16
    mode: read
  error_01:
    addr: 0x7507
    unit: ES
    mode: read
  error_02:
    addr: 0x7510
    unit: ES
    mode: read
  error_03:
    addr: 0x7519
    unit: ES
    mode: read
  error_04:
    addr: 0x7522
    unit: ES
    mode: read
  error_05:
    addr: 0x752B
    unit: ES
    mode: read
  error_06:
    addr: 0x7534
    unit: ES
    mode: read
  error_07:
    addr: 0x753D
    unit: ES
    mode: read
  error_08:
    addr: 0x7546
    unit: ES
    mode: read
  error_09:
    addr: 0x754F
    unit: ES
    mode: read
  error_10:
    addr: 0x7558
    unit: ES
    mode: read
units:
  E_TIMER:
    name: AufheizTimerSekunden
    type: u32
    factor: 10
  ES:
    name: ErrorStatus
    type: errstate
    mapping:
      [0x00]: 'Normalbetrieb'
      [0x0F]: 'Normalbetrieb-Wartung'
      [0x10]: 'Notbetrieb-Außentemp'
      [0x18]: 'Notbetrieb-Außentemp'
      [0x20]: 'Ausfall HK M2-Vorlauftemp'
      [0x21]: 'Notbetrieb HK M2- Rücklauft'
      [0x28]: 'Ausfall HK M2-Vorlauftemp'
      [0x29]: 'Notbetrieb HK M2- Rücklauft'
      [0x30]: 'Notbetrieb-Kesseltemp'
      [0x38]: 'Notbetrieb-Kesseltemp'
      [0x40]: 'Ausfall HK M3-Vorlauftemp'
      [0x41]: 'Notbetrieb HK M3-Rücklauft'
      [0x48]: 'Ausfall HK M3-Vorlauftemp'
      [0x49]: 'Notbetrieb HK M3-Rücklauft'
      [0x50]: 'Notbetrieb-Speichertemp'
      [0x51]: 'Notbetrieb-Speichertemp'
      [0x58]: 'Notbetrieb-Speichertemp'
      [0x59]: 'Notbetrieb-Speichertemp'
      [0x92]: 'Notbetrieb-Kollektortemp'
      [0x93]: 'Notbetrieb-Speichertemp.Sol'
      [0x94]: 'Notbetrieb-Speichertemp.Sol'
      [0x9A]: 'Notbetrieb-Kollektortemp'
      [0x9B]: 'Notbetrieb-Speichertemp.Sol'
      [0x9C]: 'Notbetrieb-Speichertemp.Sol'
      [0x9F]: 'Notbetrieb-Solarregelung'
      [0xB0]: 'Normalbetrieb-Abgastemp'
      [0xB1]: 'Notbetrieb-Komm-Bedienteil'
      [0xB4]: 'Notbetrieb-Störung Intern'
      [0xB5]: 'Notbetrieb-Störung Intern'
      [0xB6]: 'Notbetrieb-Störung Intern'
      [0xB7]: 'Notbetrieb-Codierstecker'
      [0xB8]: 'Normalbetrieb-Abgastemp'
      [0xB9]: 'Notbetrieb-Störung Interner'
      [0xBA]: 'Notbetrieb-HK Mischer M2'
      [0xBB]: 'Notbetrieb-HK Mischer M3'
      [0xBC]: 'Notbetrieb-Fernbedien.HK A1'
      [0xBD]: 'Notbetrieb-Fernbedien.HK M2'
      [0xBE]: 'Notbetrieb-Fernbedien.HK.M3'
      [0xC1]: 'Ausfall Anlage-ExtSIcherheit'
      [0xC2]: 'Notbetrieb-Komm. Solar'
      [0xC4]: 'Notbetrieb-Kommunikation'
      [0xC5]: 'Notbetrieb-Pumpe HK A1'
      [0xC6]: 'Notbetrieb-Pumpe HK M2'
      [0xC7]: 'Notbetrieb-Pumpe HK M3'
      [0xC9]: 'Notbetrieb-ext. Gerät'
      [0xCD]: 'Ausfall Anlagenüberwachung'
      [0xCE]: 'Notbetrieb-Schaltmodule V'
      [0xCF]: 'Notbetrieb-Komm.2Draht-Bus'
      [0xD1]: 'Ausfall Anlage: Brennerstörung'
      [0xD4]: 'Ausfall Anlage-Temp.Begrenz.'
      [0xDA]: 'Notbetrieb-Raumtemp HK A1'
      [0xDB]: 'Notbetrieb-Raumtemp HK M2'
      [0xDC]: 'Notbetrieb-Raumtemp HK M3'
      [0xDD]: 'Notbetrieb-Raumtemp HK A1'
      [0xDE]: 'Notbetrieb-Raumtemp HK M2'
      [0xDF]: 'Notbetrieb-Raumtemp HK M3'
      [0xE0]: 'Ausfall Anlage-2 Draht-Bus'
      [0xE1]: 'Ausfall Anlage-2 Draht-Bus'
      [0xE2]: 'Ausfall Anlage-2 Draht-Bus'
      [0xE3]: 'Ausfall Anlage-2 Draht-Bus'
      [0xE4]: 'Ausfall Anlage-2 Draht-Bus'
      [0xE5]: 'Ausfall Anlage-2 Draht-Bus'
      [0xE6]: 'Ausfall Anlage-2 Draht-Bus'
      [0xE7]: 'Ausfall Anlage-2 Draht-Bus'
      [0xE8]: 'Ausfall Anlage-2 Draht-Bus'
      [0xE9]: 'Ausfall Anlage-2 Draht-Bus'
      [0xEA]: 'Ausfall Anlage-2 Draht-Bus'
      [0xEB]: 'Ausfall Anlage-2 Draht-Bus'
      [0xEC]: 'Ausfall Anlage-2 Draht-Bus'
      [0xED]: 'Ausfall Anlage-2 Draht-Bus'
      [0xEE]: 'Ausfall Anlage-2 Draht-Bus'
      [0xEF]: 'Ausfall Anlage-2 Draht-Bus'
      [0xF0]: 'Ausfall Anlage-2 Draht-Bus'
      [0xF1]: 'Ausfall Anlage-2 Draht-Bus'
      [0xF2]: 'Ausfall Anlage-2 Draht-Bus'
      [0xF3]: 'Ausfall Anlage-2 Draht-Bus'
      [0xF4]: 'Ausfall Anlage-2 Draht-Bus'
      [0xF5]: 'Ausfall Anlage-2 Draht-Bus'
      [0xF6]: 'Ausfall Anlage-2 Draht-Bus'
      [0xF7]: 'Ausfall Anlage-2 Draht-Bus'
      [0xF8]: 'Ausfall Anlage-2 Draht-Bus'
      [0xF9]: 'Ausfall Anlage-2 Draht-Bus'
      [0xFA]: 'Ausfall Anlage-2 Draht-Bus'
      [0xFB]: 'Ausfall Anlage-2 Draht-Bus'
      [0xFC]: 'Ausfall Anlage-2 Draht-Bus'
      [0xFD]: 'Ausfall Anlage-2 Draht-Bus'
      [0xFE]: 'Ausfall Anlage-2 Draht-Bus'
      [0xFF]: 'Ausfall Anlage-2 Draht-Bus'
  B_FW:
    name: Frostwarnung
    type: enum
    mapping:
      [0x01]: 'ON'
      [0x00]: 'OFF'
  HKLN:
    name: Niveau
    type: i8
  HKLS:
    name: Steigung
    type: i8
    factor: 10
  E_HKP:
    name: HeizkreisPumpenBefehl
    type: enum
    mapping:
      [0x00]: OFF
      [0x01]: ON
      [0x02]: ON
      [0x03]: RED
  E_BA:
    name: Betriebsart
    type: enum
    mapping:
      [0x00]: NWW # Nur WW
      [0x01]: RED # Dauernd Reduziert
      [0x02]: NRM # Dauernd Normal
      [0x03]: HWW # Heizen + WW
      [0x04]: HWW # Heizen + WW
      [0x05]: OFF # Abschalt
  E_WWF:
    name: Warmwasser-Freigabe
    type: enum
    mapping:
      [0x00]: Freigabe aus
      [0x01]: Freigabe nach WW-Schaltzeiten
      [0x02]: Freigabe durch Party/Externe Umschaltung
  COL:
    name: Counter Liter
    type: u32
    factor: 1000
  CO:
    name: Anzahl
    type: u32
  HS:
    name: Stunden
    type: u32
    factor: 3600
  TD:
    name: Temperatur
    type: i16
    factor: 10
  T1U:
    name: Temperatur
    type: u8
  B_FB:
    name: FerienBetrieb
    type: enum
    mapping:
      [0x12]: OFF
      [0x01]: ON
  E_ST:
    name: Status
    type: enum
    mapping:
      [0x00]: OFF
      [0x01]: ON
  E_TS:
    name: SensorStatus
    type: enum
    mapping:
      [0x00]: OK
      [0x01]: Kurzschluss
      [0x02]: Unterbruch
      [0x03]: Referenzfehler
      [0x04]: Referenz unter Min
      [0x05]: Referenz über Max
      [0x06]: nicht vorhanden
      [0x07]: Check
      [0x08]: Fehler
      [0x09]: Kom Fehler
  CT:
    name: Schaltzeit
    type: cycletime
  E_BA2:
    name: Betriebsart
    type: enum
    mapping:
      [0x00]: NWW
      [0x01]: RED
      [0x02]: NRM
      [0x03]: HWW
      [0x04]: HWW
      [0x05]: OFF
  TI:
    name: SystemTime
    type: systime
  DT:
    name: SystemKennung
    type: enum
    mapping:
      # [0x20, 0x54, 0x00]: GWG_BT2
      # [0x20, 0x53, 0x01]: GWG_VBEM
      # [0x20, 0x53, 0x02]: GWG_VBES
      # [0x20, 0x53, 0x10]: GWG_VBT2
      # [0x20, 0x53, 0x08]: GWG_VWMS
      [0x20, 0xB4]: V050HK1M
      [0x20, 0xAC]: V050HK1S
      [0x20, 0xAA]: V050HK1W
      [0x20, 0xAD]: V050HK3S
      [0x20, 0xAB]: V050HK3W
      [0x20, 0xA0]: V100GC1
      [0x20, 0x91]: V100KC2
      [0x20, 0x92]: V150KB1
      [0x20, 0xA4]: V200GW1
      [0x20, 0x94]: V200KW1
      [0x20, 0x98]: V200KW2
      [0x20, 0xA5]: V300GW2
      [0x20, 0x9C]: V300KW3
      [0x20, 0xB8]: V333MW1
      [0x20, 0xB9]: V333MW1S
      [0x20, 0xBA]: V333MW2
      [0x20, 0x33]: VBC550P
      [0x20, 0x32]: VBC550S
      [0x20, 0x47]: VBC700_AW
      [0x20, 0x46]: VBC700_BW_WW
      [0x20, 0xC0]: VDensHC1
      [0x20, 0xC1]: VDensHC2
      [0x20, 0xC2]: VDensHO1
      [0x20, 0xC3]: VPendHC1
      [0x20, 0xC4]: VPendHC2
      [0x20, 0xC5]: VPendHO1
      [0x20, 0xC6]: VPlusHC1
      [0x20, 0xC7]: VPlusHC2
      [0x20, 0xC8]: VPlusHO1
      [0x20, 0xC9]: VScotHC1
      [0x20, 0xCA]: VScotHC2
      [0x20, 0xCB]: VScotHO1
